### ISSUE TITLE
Move to Vercel

### ISSUE THREAD

**Issue by okonet** [okonet/danielamulle.at#96]
The biggest challenge is the GitHub auth which is required for the CMS to work. See https://www.netlifycms.org/docs/github-backend/

Potentially can be solved with https://github.com/bericp1/netlify-cms-oauth-provider-node or https://github.com/vencax/netlify-cms-github-oauth-provider

Also see https://docs.netlify.com/visitor-access/oauth-provider-tokens/#using-an-authentication-provider

### Todo

- [ ] Move to component-driven org
- [ ] Ensure that the GitHub auth works with Netlify CMS (replacement for Netlify Identity service needed)
- [ ] Move to Vercel
